# Generated by Django 4.1 on 2022-08-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Propiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("precio", models.IntegerField()),
                ("ladrillos", models.IntegerField()),
                ("ladrillosEnventa", models.IntegerField()),
                ("imagen", models.ImageField(upload_to="")),
            ],
        ),
    ]
